import { projectSection } from './ui-navigation';
import { test, expect, type Page } from '@playwright/test';
import { projectInput } from '../support/project-fixture';
import { workItemDefaults } from '../../shared/work-items';
import { dayIndex, dateAt, periods, newWeekConvention } from '../../shared/plans';

async function login(page: Page, role: string) {
  await page.goto('/masuk');
  await page.getByLabel('Email', { exact: true }).fill(`${role}@example.test`);
  await page.getByLabel('Kata sandi', { exact: true }).fill(process.env.SIMP_TEST_PASSWORD!);
  await page.getByRole('button', { name: 'Masuk', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Proyek Anda' })).toBeVisible();
}
test('pemeriksaan target memilih pekerjaan yang belum 100 persen', async ({ page }, info) => {
  await login(page, 'team_leader');
  const me = await (await page.request.get('/api/auth/me')).json();
  const start = new Date().toISOString().slice(0,10), end = dateAt(dayIndex(start) + 13);
  const headers = { origin: 'http://127.0.0.1:5174' };
  const response = await page.request.post('/api/projects', { headers, data: projectInput({ projectCode: `TARGET-${info.project.name}-${Date.now()}`, teamLeaderId: me.user.id, startDate: start, endDate: end }) });
  expect(response.status()).toBe(201);
  const project = (await response.json()).project;
  for (const [code, name] of [['I.1', 'Papan Nama Proyek'], ['IV.A.8', 'Pengelasan']]) {
    const created = await page.request.post(`/api/projects/${project.id}/work-items`, { headers, data: { ...workItemDefaults, code, name, unit: 'm', contractVolume: '1', unitPrice: '100' } });
    expect(created.status()).toBe(201);
  }
  await page.goto(`/proyek/${project.id}/rencana`);
  await page.getByRole('button', { name: 'Buat Rencana Awal' }).click();
  await page.getByRole('button', { name: 'Lanjut ke Target' }).click();
  await page.getByLabel('Pekerjaan yang diatur').selectOption({ label: 'I.1 · Papan Nama Proyek' });
  await page.getByLabel(/Minggu 1/).fill('100');
  await page.getByRole('button', { name: 'Periksa Rencana' }).click();
  await expect(page.getByRole('alert')).toContainText('IV.A.8 · Pengelasan');
  await expect(page.locator('#plan-item option:checked')).toHaveText('IV.A.8 · Pengelasan');
  await expect(page.locator('#plan-item')).toBeFocused();
  await expect(page.locator('.target-total')).toContainText('0,00%');
  await page.getByLabel(/Minggu 2/).fill('100');
  await page.getByRole('button', { name: 'Periksa Rencana' }).click();
  await expect(page.getByText('Langkah 3 dari 3')).toBeVisible();
});
test('TL menerbitkan baseline dan revisi masa depan, memilih cutoff dan membandingkan versi', async ({ page }, info) => {
  test.setTimeout(90000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await login(page, 'team_leader');
  const me = await (await page.request.get('/api/auth/me')).json();
  const start = new Date().toISOString().slice(0,10), end = dateAt(dayIndex(start) + 13);
  const headers = { origin: 'http://127.0.0.1:5174' };
  const response = await page.request.post('/api/projects', { headers, data: projectInput({ projectCode: `PLAN-${info.project.name}-${Date.now()}`, teamLeaderId: me.user.id, startDate: start, endDate: end }) });
  expect(response.status()).toBe(201); const project = (await response.json()).project;
  const item = await page.request.post(`/api/projects/${project.id}/work-items`, { headers, data: { ...workItemDefaults, code: 'A', name: 'Pekerjaan Rencana UI', unit: 'm', contractVolume: '1000', unitPrice: '100' } });
  expect(item.status()).toBe(201);
  await page.goto(`/proyek/${project.id}`);
  await projectSection(page,'rencana');
  await expect(page.getByRole('heading', { name: 'Belum ada Rencana Awal' })).toBeVisible();
  await page.getByRole('button', { name: 'Buat Rencana Awal', exact: true }).click();
  await page.getByRole('button', { name: 'Lanjut ke Target' }).click();
  await page.getByRole('button', { name: 'Periksa Rencana', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('harus tepat 100%');
  await page.getByRole('button', { name: 'Bagi Rata Pekerjaan Ini' }).click();
  await page.screenshot({ path: info.outputPath('editor-target.png'), fullPage: true });
  await page.getByRole('button', { name: 'Periksa Rencana', exact: true }).click();
  await page.getByRole('button', { name: 'Tetapkan Rencana', exact: true }).click();
  await expect(page.getByText('Rencana berhasil diterbitkan.', { exact: true })).toBeVisible();
  await expect(page.locator('.plan-period-table tbody tr')).toHaveCount(periods(start, end, 'WEEKLY', newWeekConvention).length);
  await expect(page.locator('.plan-period-table tbody tr').last()).toContainText('100,00%');
  await page.reload();
  await expect(page.getByRole('heading', { name: 'V1 · Rencana Awal', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Buat Perubahan Rencana', exact: true }).click();
  const future = dateAt(dayIndex(project.today) + 1);
  await page.getByLabel('Tanggal berlaku', { exact: true }).fill(future);
  await page.getByLabel('Tanggal selesai versi', { exact: true }).fill(dateAt(dayIndex(end) + 7));
  await page.getByLabel('Sumber target', { exact: true }).selectOption('MONTHLY');
  await page.getByLabel('Alasan', { exact: true }).fill('Material terlambat sehingga jadwal diperpanjang');
  await page.getByRole('button', { name: 'Lanjut ke Target' }).click();
  await page.getByRole('button', { name: 'Bagi Rata Pekerjaan Ini' }).click();
  await page.getByRole('button', { name: 'Periksa Rencana', exact: true }).click();
  await page.getByRole('button', { name: 'Tetapkan Rencana', exact: true }).click();
  await expect(page.getByText('Rencana berhasil diterbitkan.', { exact: true })).toBeVisible();
  await expect(page.getByTestId('effective-plan')).toContainText('Rencana Awal');
  await expect(page.getByText('Belum berlaku', { exact: true })).toBeVisible();
  await page.getByText('Riwayat dan perbandingan rencana',{exact:true}).click();
  await page.getByLabel('Bandingkan dengan', { exact: true }).selectOption({ label: 'V1 · Rencana Awal' });
  await expect(page.locator('.plan-period-table').last().locator('tbody tr').last()).toContainText('100,00%');
  await expect(page.locator('.plan-period-table').first()).toContainText('33,33%');
  await page.getByLabel('Tanggal pemeriksaan', { exact: true }).fill(future);
  await page.getByRole('button', { name: 'Tampilkan yang Berlaku' }).click();
  await expect(page.getByTestId('effective-plan')).toContainText('Perubahan Rencana 1');
  await page.getByLabel('Tampilan periode', { exact: true }).selectOption('MONTHLY');
  await expect(page.locator('.plan-period-table').first()).toContainText('100,00%');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('perbandingan-rencana.png'), fullPage: true });
  await page.goto(`/proyek/${project.id}/pekerjaan`);
  await expect(page.getByRole('button', { name: 'Tambah Pekerjaan', exact: true })).toHaveCount(0);
  expect(errors).toEqual([]);
});
test('Owner membaca rencana, tidak dapat menerbitkan dan dapat memulihkan kegagalan koneksi', async ({ page }, info) => {
  await login(page, 'owner'); await page.goto('/proyek');
  await page.getByRole('link', { name: 'Proyek Penugasan Uji', exact: true }).click();
  await page.route('**/api/projects/*/plans', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Rencana belum dapat dimuat.' } }) }));
  await projectSection(page,'rencana');
  await expect(page.getByRole('alert')).toContainText('Rencana belum dapat dimuat.');
  await page.unroute('**/api/projects/*/plans');
  await page.getByRole('button', { name: 'Coba Lagi', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'V1 · Rencana Awal', exact: true })).toBeVisible();
  await expect(page.locator('.plan-period-table')).toContainText('100,00%');
  await expect(page.getByRole('button', { name: 'Buat Perubahan Rencana', exact: true })).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('owner-rencana.png'), fullPage: true });
});
