import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import sharp from 'sharp';
import { projectInput } from '../support/project-fixture';
import { workItemDefaults } from '../../shared/work-items';
import { emptyReport } from '../../shared/reports';
import { periods, newWeekConvention } from '../../shared/plans';

test('T07 progress nyata, sumber, filter, cutoff dan pemulihan gagal pada komputer/HP', async ({ page }, info) => {
  test.setTimeout(120000);
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/masuk'); await page.getByLabel('Email', { exact: true }).fill('team_leader@example.test');
  await page.getByLabel('Kata sandi', { exact: true }).fill(process.env.SIMP_TEST_PASSWORD!);
  await page.getByRole('button', { name: 'Masuk', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Proyek Anda' })).toBeVisible();
  const headers = { origin: 'http://127.0.0.1:5174' }, me = await (await page.request.get('/api/auth/me')).json();
  const created = await page.request.post('/api/projects', { headers, data: projectInput({ projectCode: `PROGRESS-${info.project.name}-${Date.now()}`, teamLeaderId: me.user.id }) });
  expect(created.status()).toBe(201); const project = (await created.json()).project;
  const root = `/api/projects/${project.id}`;
  const items = [];
  for (const [code, volume] of [['A', '1000'], ['B', '9000']]) {
    const result = await page.request.post(`${root}/work-items`, { headers, data: { ...workItemDefaults, code, name: `Pekerjaan ${code}`, unit: 'm', contractVolume: volume, unitPrice: '100' } });
    expect(result.status()).toBe(201); items.push((await result.json()).item);
  }
  const context = await (await page.request.get(`${root}/plans`)).json();
  const planParts = periods(project.startDate, project.endDate, 'WEEKLY', newWeekConvention);
  expect((await page.request.post(`${root}/plans`, { headers, data: { previousVersionId: null, basisToken: context.basisToken, name: 'Rencana Awal', reason: 'Tes progress', description: '', startDate: project.startDate, endDate: project.endDate, effectiveDate: project.startDate, granularity: 'WEEKLY', items: items.map(item => ({ workItemId: item.id, targets: planParts.map((_, index) => index === 0 ? '50' : index === planParts.length - 1 ? '50' : '0') })) } })).status()).toBe(201);
  const activityId = randomUUID();
  const saved = await page.request.post(`${root}/reports`, { headers, data: { ...emptyReport(project.startDate), activities: [{ id: activityId, workItemId: items[0].id, description: 'Galian sumber progress', quantity: '250', location: 'Utara', notes: '' }] } });
  expect(saved.status()).toBe(201); const report = (await saved.json()).id;
  const png = await sharp({ create: { width: 8, height: 8, channels: 3, background: '#397860' } }).png().toBuffer();
  expect((await page.request.post(`${root}/reports/${report}/photos`, { headers, data: { editVersion: 1, activityId, caption: 'Foto tes', location: 'Utara', takenDate: project.startDate, mime: 'image/png', data: png.toString('base64') } })).status()).toBe(201);
  expect((await page.request.post(`${root}/reports/${report}/submit`, { headers, data: { editVersion: 2 } })).status()).toBe(204);
  expect((await page.request.post(`${root}/reports/${report}/reviews`, { headers, data: { editVersion: 3, kind: 'APPROVE', note: '' } })).status()).toBe(204);
  await page.goto(`/proyek/${project.id}`); await page.getByRole('link', { name: 'Rincian kemajuan', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Rincian kemajuan', exact: true })).toBeVisible();
  const total = page.locator('section').filter({ has: page.getByRole('heading', { name: 'Total proyek', exact: true }) });
  await expect(total.getByRole('row').filter({ hasText: 'Total sampai tanggal ini' })).toContainText('2,500000%');
  await expect(total).toContainText('-97,500000');
  await page.getByLabel('Pekerjaan', { exact: true }).selectOption(items[0].id);
  await page.getByRole('button', { name: 'Tampilkan Kemajuan' }).click();
  await expect(page.getByRole('heading', { name: 'B — Pekerjaan B' })).toHaveCount(0);
  await page.getByText('Laporan sumber perhitungan',{exact:true}).click();
  await expect(page.getByRole('link', { name: 'LH-00001 · revisi 1' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('progress.png'), fullPage: true });
  await page.route(`**${root}/progress*`, route => route.fulfill({ status: 503, json: { message: 'Tes koneksi terputus' } }));
  await page.getByRole('button', { name: 'Tampilkan Kemajuan' }).click(); await expect(page.getByRole('alert')).toBeVisible();
  await page.unroute(`**${root}/progress*`); await page.getByRole('button', { name: 'Coba Lagi' }).click();
  await expect(total.getByRole('row').filter({ hasText: 'Total sampai tanggal ini' })).toContainText('2,500000%');
  await page.getByText('Laporan sumber perhitungan',{exact:true}).click();
  await page.getByRole('link', { name: 'LH-00001 · revisi 1' }).click(); await expect(page.getByRole('heading', { name: 'LH-00001', exact: true })).toBeVisible();
  await page.goto(`/proyek/${project.id}/laporan-berkala`);
  await expect(page.getByRole('heading', { name: 'Minggu ke-2', exact: true })).toBeVisible();
  let summary = page.locator('section').filter({ has: page.getByRole('heading', { name: 'Ringkasan laporan', exact: true }) });
  await expect(summary.getByRole('row').filter({ hasText: 'Sebelumnya' })).toContainText('2,500000%');
  await expect(summary.getByRole('row').filter({ hasText: 'Periode ini' })).toContainText('0,000000%');
  await page.getByLabel('Periode laporan', { exact: true }).selectOption('1');
  await page.getByRole('button', { name: 'Tampilkan Laporan' }).click();
  await expect(page.getByRole('heading', { name: 'Minggu ke-1', exact: true })).toBeVisible();
  await expect(summary.getByRole('row').filter({ hasText: 'Periode ini' })).toContainText('2,500000%');
  await page.getByLabel('Jenis laporan').selectOption('MONTHLY');
  await expect(page.getByRole('heading', { name: 'Bulan ke-1', exact: true })).toBeVisible();
  await expect(page.getByText('2026-07-16 sampai 2026-07-23 (8 hari, inklusif).')).toBeVisible();
  await page.getByText('Rincian sumber dan persetujuan',{exact:true}).click();
  await expect(page.getByRole('link', { name: 'LH-00001 · revisi 1' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('laporan-berkala.png'), fullPage: true });
  await page.route(`**${root}/period-reports*`, route => route.fulfill({ status: 503, json: { message: 'Tes koneksi' } }));
  await page.getByRole('button', { name: 'Tampilkan Laporan' }).click(); await expect(page.getByRole('alert')).toBeVisible();
  await page.unroute(`**${root}/period-reports*`); await page.getByRole('button', { name: 'Coba Lagi' }).click();
  await expect(page.getByRole('heading', { name: 'Bulan ke-1', exact: true })).toBeVisible();
  await page.goto(`/proyek/${project.id}/ringkasan`);
  await page.getByText('Grafik rencana dan capaian',{exact:true}).click();
  await expect(page.getByRole('img', { name: 'Grafik Rencana Awal, Rencana Terbaru dan Capaian' })).toBeVisible();
  await expect(page.locator('.monitor-cards')).toContainText('2,50%');
  await page.getByText('Lihat angka grafik', { exact: true }).click();
  await expect(page.locator('details').filter({has:page.getByText('Lihat angka grafik',{exact:true})}).last()).toContainText('2,50');
  const monitoring = await (await page.request.get(`${root}/monitoring`)).json();
  await expect(page.getByRole('heading', { name: 'Tanggal dan pembanding grafik', exact: true })).toBeVisible();
  await page.getByLabel('Pembanding grafik').selectOption(monitoring.progress.basisVersionId);
  await page.getByRole('button', { name: 'Tampilkan Ringkasan' }).click();
  await expect(page.locator('.monitor-cards')).toContainText('2,50%');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('monitoring.png'), fullPage: true });
  await page.goto(`/proyek/${project.id}/dokumentasi`);
  await expect(page.getByRole('heading', { name: 'Filter foto', exact: true })).toBeVisible();
  await expect(page.getByRole('img', { name: 'Foto tes', exact: true })).toBeVisible();
  await page.getByLabel('Pekerjaan foto').selectOption(items[0].id);
  await page.getByLabel('Laporan sumber foto').selectOption(report);
  await page.getByLabel('Pengunggah foto').selectOption(me.user.id);
  await page.getByRole('button', { name: 'Saring Foto' }).click();
  await expect(page.getByRole('img', { name: 'Foto tes', exact: true })).toBeVisible();
  await page.getByLabel('Foto dari tanggal').fill(project.endDate);
  await page.getByRole('button', { name: 'Saring Foto' }).click();
  await expect(page.getByText('Belum ada foto yang sesuai atau dapat diakses.')).toBeVisible();
  await page.goto(`/proyek/${project.id}/riwayat`);
  await expect(page.getByRole('heading', { name: 'Laporan disetujui', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Rencana diterbitkan', exact: true })).toBeVisible();
  await page.screenshot({ path: info.outputPath('riwayat.png'), fullPage: true });
  await page.goto(`/proyek/${project.id}/ekspor`);
  await page.getByRole('button',{name:'Tampilkan Laporan'}).click();
  await expect(page.getByRole('heading',{name:'Rekap Kemajuan',exact:true})).toBeVisible();
  await page.getByText('Pratinjau cetak',{exact:true}).click();
  const workbook=page.getByRole('img',{name:'Layout workbook Progress-1',exact:true});await expect(workbook).toBeVisible();await workbook.evaluate((img:HTMLImageElement)=>img.decode());
  await page.getByText('Pilihan cetak',{exact:true}).click();
  await page.getByLabel('Gunakan logo dari workbook contoh',{exact:true}).uncheck();await page.getByRole('button',{name:'Tampilkan Laporan'}).click();await expect(page.getByRole('button',{name:'Unduh PDF',exact:true})).toBeEnabled();
  for(const [button,extension] of [['Unduh PDF','.pdf'],['Unduh Excel','.xlsx']]){
    const pending=page.waitForEvent('download');await page.getByRole('button',{name:button,exact:true}).click();const download=await pending;expect(download.suggestedFilename().endsWith(extension)).toBe(true);await download.saveAs(info.outputPath(`progress${extension}`));expect(await download.failure()).toBeNull();
  }
  for(const kind of ['DAILY','WEEKLY','MONTHLY','CURVE','WORKFORCE','MATERIALS','PROBLEMS']){
    await page.getByLabel('Jenis laporan',{exact:true}).selectOption(kind);
    if(kind==='DAILY')await page.getByLabel('Laporan harian',{exact:true}).selectOption(report);
    await page.getByRole('button',{name:'Tampilkan Laporan'}).click();await expect(page.getByRole('button',{name:'Unduh PDF',exact:true})).toBeEnabled();
    await expect(page.getByRole('alert')).toHaveCount(0);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  }
  await page.screenshot({path:info.outputPath('ekspor.png'),fullPage:true});
  await page.goto(`/proyek/${project.id}/laporan`);
  await expect(page.getByRole('heading', { name: /^Filter laporan/ })).toBeVisible();
  await page.getByLabel('Minggu ke-', {exact:true}).fill('2');await page.getByRole('button',{name:'Terapkan Filter'}).click();await expect(page.getByText('Belum ada laporan yang dapat ditampilkan')).toBeVisible();
  await page.getByRole('button',{name:'Bersihkan Filter'}).click();await expect(page.getByRole('link',{name:'Buka Laporan',exact:true})).toHaveCount(1);
  await page.getByLabel('Tanggal awal',{exact:true}).fill(project.startDate);await page.getByLabel('Tanggal akhir',{exact:true}).fill(project.endDate);await page.getByLabel('Minggu ke-',{exact:true}).fill('1');await page.getByLabel('Bulan ke-',{exact:true}).fill('1');await page.getByLabel('Status laporan',{exact:true}).selectOption('APPROVED');await page.getByLabel('Pembuat laporan',{exact:true}).selectOption(me.user.id);await page.getByRole('button',{name:'Terapkan Filter'}).click();await expect(page.getByRole('link',{name:'Buka Laporan',exact:true})).toHaveCount(1);
  let release:()=>void=()=>{};const gate=new Promise<void>(resolve=>{release=resolve;});
  await page.route(`**${root}/reports?*`,async route=>{const response=await route.fetch();if(new URL(route.request().url()).searchParams.get('status')==='DRAFT')await gate;await route.fulfill({response});});
  try{
    const started=page.waitForRequest(r=>r.url().includes(`${root}/reports?`)&&new URL(r.url()).searchParams.get('status')==='DRAFT');
    await page.getByLabel('Status laporan',{exact:true}).selectOption('DRAFT');await page.getByRole('button',{name:'Terapkan Filter'}).click();await started;
    await page.getByLabel('Status laporan',{exact:true}).selectOption('APPROVED');await page.getByRole('button',{name:'Terapkan Filter'}).click();
    const old=page.waitForResponse(r=>r.url().includes(`${root}/reports?`)&&new URL(r.url()).searchParams.get('status')==='DRAFT');release();await(await old).finished();await page.waitForTimeout(200);
    await expect(page.getByRole('link',{name:'Buka Laporan',exact:true})).toHaveCount(1);
  }finally{release();}
  expect(errors).toEqual([]);
});

test('T08 Owner membuka periode kosong tanpa tindakan mengubah data', async ({ page }) => {
  await page.goto('/masuk'); await page.getByLabel('Email', { exact: true }).fill('owner@example.test');
  await page.getByLabel('Kata sandi', { exact: true }).fill(process.env.SIMP_TEST_PASSWORD!);
  await page.getByRole('button', { name: 'Masuk', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Proyek Anda' })).toBeVisible();
  const list = await (await page.request.get('/api/projects?q=BROWSER-SEED')).json();
  await page.goto(`/proyek/${list.projects[0].id}`);
  await page.getByRole('link', { name: 'Baca rekap laporan', exact: true }).click();
  await page.getByText('Rincian sumber dan persetujuan',{exact:true}).click();
  await expect(page.getByText('Belum ada laporan harian disetujui yang dapat Anda lihat dalam periode ini.', { exact: false })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Simpan', exact: false })).toHaveCount(0);
  await page.getByLabel('Jenis laporan').selectOption('MONTHLY');
  await expect(page.getByRole('heading', { name: 'Bulan ke-1', exact: true })).toBeVisible();
});

test('T09 Administrator melihat kartu dan aktivitas sistem, error ringkasan dapat dipulihkan',async({page})=>{
 await page.goto('/masuk');await page.getByLabel('Email',{exact:true}).fill('admin@example.test');await page.getByLabel('Kata sandi',{exact:true}).fill(process.env.SIMP_TEST_PASSWORD!);await page.getByRole('button',{name:'Masuk',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Proyek Anda',exact:true})).toBeVisible();
 await page.route('**/api/dashboard',route=>route.fulfill({status:503,json:{error:{message:'Tes kegagalan ringkasan'}}}));
 await page.goto('/ringkasan');await expect(page.getByRole('alert')).toContainText('Tes kegagalan');
 await page.unroute('**/api/dashboard');await page.getByRole('button',{name:'Coba Lagi',exact:true}).click();
 await expect(page.locator('.monitor-cards')).toContainText('Pengguna');await expect(page.getByText('Aktivitas sistem terbaru',{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
