import { projectSection } from './ui-navigation';
import { test,expect,type Page } from '@playwright/test';
import sharp from 'sharp';
import { randomBytes } from 'node:crypto';
import { projectInput } from '../support/project-fixture';
import { workItemDefaults } from '../../shared/work-items';

async function login(page:Page,role:string){await page.goto('/masuk');await page.getByLabel('Email',{exact:true}).fill(`${role}@example.test`);await page.getByLabel('Kata sandi',{exact:true}).fill(process.env.SIMP_TEST_PASSWORD!);await page.getByRole('button',{name:'Masuk',exact:true}).click();await expect(page.getByRole('heading',{name:'Proyek Anda'})).toBeVisible();}
async function photoVisible(page:Page){const photo=page.getByRole('img',{name:'Foto pekerjaan galian',exact:true});await expect(photo).toBeVisible();await photo.scrollIntoViewIfNeeded();await expect.poll(()=>photo.evaluate(image=>(image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);}
test('laporan lengkap tersimpan, foto dibuka ulang, dokumentasi pekerjaan dan pengiriman terkunci',async({page},info)=>{
  test.setTimeout(120000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await login(page,'team_leader');const me=await(await page.request.get('/api/auth/me')).json(),headers={origin:'http://127.0.0.1:5174'};
  const created=await page.request.post('/api/projects',{headers,data:projectInput({projectCode:`REPORT-${info.project.name}-${Date.now()}`,teamLeaderId:me.user.id})});expect(created.status()).toBe(201);const project=(await created.json()).project;
  const itemResponse=await page.request.post(`/api/projects/${project.id}/work-items`,{headers,data:{...workItemDefaults,code:'A',name:'Galian UI',unit:'m³',contractVolume:'1000',unitPrice:'100'}});expect(itemResponse.status()).toBe(201);const item=(await itemResponse.json()).item;
  const plan=await(await page.request.get(`/api/projects/${project.id}/plans`)).json();expect((await page.request.post(`/api/projects/${project.id}/plans`,{headers,data:{previousVersionId:null,basisToken:plan.basisToken,name:'Rencana Awal',reason:'Rencana pengujian',description:'',startDate:project.startDate,endDate:project.endDate,effectiveDate:project.startDate,granularity:'WEEKLY',items:[{workItemId:item.id,targets:['50','50']}]}})).status()).toBe(201);
  await page.goto(`/proyek/${project.id}`);await projectSection(page,'laporan');await page.getByRole('button',{name:'Buat Laporan Harian',exact:true}).click();
  await page.getByRole('button',{name:'Simpan Sementara',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Uraian kegiatan wajib');
  await page.getByLabel('Tanggal laporan',{exact:true}).fill(project.startDate);await page.getByLabel('Pekerjaan 1',{exact:true}).selectOption(item.id);await page.getByLabel('Uraian kegiatan 1',{exact:true}).fill('Galian tanah di lokasi utara');await page.getByLabel('Volume kegiatan 1',{exact:true}).fill('75');await page.getByLabel('Lokasi kegiatan 1',{exact:true}).fill('STA 0+000');
  await page.getByRole('button',{name:'Lanjut',exact:true}).click();await page.getByRole('button',{name:'Tambah Tenaga Kerja',exact:true}).click();await page.getByLabel('Jenis tenaga kerja 1',{exact:true}).selectOption('Operator');await page.getByLabel('Jumlah orang 1',{exact:true}).fill('-1');await page.getByRole('button',{name:'Simpan Sementara',exact:true}).click();await expect(page.getByRole('alert')).toContainText('tidak boleh negatif');await page.getByLabel('Jumlah orang 1',{exact:true}).fill('3');await page.getByLabel('Identitas opsional 1',{exact:true}).fill('OP-01, OP-02, OP-03');await page.getByRole('button',{name:'Tambah Cuaca',exact:true}).click();
  await page.getByRole('button',{name:'Lanjut',exact:true}).click();await page.getByRole('button',{name:'Tambah Material atau Alat',exact:true}).click();await page.getByLabel('Penerimaan 1',{exact:true}).selectOption('DITOLAK');await page.getByLabel('Nama material atau alat 1',{exact:true}).fill('Pipa PVC');await page.getByLabel('Jumlah material 1',{exact:true}).fill('5');await page.getByLabel('Satuan material 1',{exact:true}).fill('m');await page.getByRole('button',{name:'Simpan Sementara',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Alasan penolakan');await page.getByLabel('Alasan penolakan 1',{exact:true}).fill('Material retak');
  await page.getByRole('button',{name:'Tambah Masalah',exact:true}).click();await page.getByLabel('Uraian masalah 1',{exact:true}).fill('Akses jalan licin');await page.getByLabel('Dampak 1',{exact:true}).fill('Pengiriman tertunda');await page.getByLabel('Penyelesaian 1',{exact:true}).fill('Ditambahkan kerikil');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('form-laporan.png'),fullPage:true});await page.getByRole('button',{name:'Lanjut',exact:true}).click();await page.getByLabel('Catatan umum',{exact:true}).fill('Kegiatan berjalan bertahap');await page.getByRole('button',{name:'Simpan & Lanjut ke Foto',exact:true}).click();await expect(page.getByRole('heading',{name:'LH-00001',exact:true})).toBeVisible();
  const reportUrl=page.url();await page.reload();await page.getByText('Identitas laporan dan kontrak',{exact:true}).click();await expect(page.getByText('Total tenaga kerja:',{exact:false})).toContainText('3 orang');await expect(page.getByRole('row').filter({hasText:'Pipa PVC'})).toContainText('DITOLAK');await expect(page.getByRole('row').filter({hasText:'Akses jalan licin'})).toBeVisible();
  await page.getByRole('button',{name:'Ubah Laporan',exact:true}).click();await page.getByLabel('Catatan kegiatan 1',{exact:true}).fill('Catatan setelah pemeriksaan ulang');await page.getByRole('button',{name:'Simpan Sementara',exact:true}).click();await expect(page.getByText('Isian tersimpan. Lanjutkan melengkapi foto dan periksa sebelum dikirim.',{exact:true})).toBeVisible();await expect(page.getByRole('row').filter({hasText:'Pipa PVC'})).toContainText('DITOLAK');
  await page.getByRole('button',{name:'Periksa Sebelum Kirim',exact:true}).click();await page.getByRole('button',{name:'Kirim untuk Diperiksa',exact:true}).click();await expect(page.getByRole('alert')).toContainText('minimal satu foto');
  await page.getByLabel('Berkas foto',{exact:true}).setInputFiles({name:'palsu.png',mimeType:'image/png',buffer:Buffer.from('bukan gambar')});await page.getByLabel('Keterangan foto',{exact:true}).fill('Foto pekerjaan galian');await page.getByRole('button',{name:'Unggah Foto',exact:true}).click();await expect(page.getByRole('alert').last()).toContainText('Isi berkas');
  const png=await sharp({create:{width:320,height:180,channels:3,background:'#397860'}}).png().toBuffer();await page.getByLabel('Berkas foto',{exact:true}).setInputFiles({name:'galian.png',mimeType:'image/png',buffer:png});await page.getByLabel('Lokasi foto',{exact:true}).fill('STA 0+000');await page.getByRole('button',{name:'Unggah Foto',exact:true}).click();await photoVisible(page);
  const large=await sharp(randomBytes(2000*2000*3),{raw:{width:2000,height:2000,channels:3}}).jpeg({quality:90}).toBuffer();expect(large.length).toBeGreaterThan(2.8*1024*1024);expect(large.length).toBeLessThan(5*1024*1024);await page.getByLabel('Berkas foto',{exact:true}).setInputFiles({name:'galian-besar.jpg',mimeType:'image/jpeg',buffer:large});await page.getByLabel('Keterangan foto',{exact:true}).fill('Foto besar');await page.getByRole('button',{name:'Unggah Foto',exact:true}).click();await expect(page.getByRole('img',{name:'Foto besar',exact:true})).toBeVisible();await page.reload();await photoVisible(page);await expect(page.getByRole('img',{name:'Foto besar',exact:true})).toBeVisible();
  await page.goto(`/proyek/${project.id}/pekerjaan`);await page.getByRole('link',{name:'Dokumentasi A',exact:true}).click();await photoVisible(page);await page.goto(reportUrl);
  await page.getByRole('button',{name:'Periksa Sebelum Kirim',exact:true}).click();await page.getByRole('button',{name:'Kirim untuk Diperiksa',exact:true}).click();await expect(page.locator('.page-heading').getByText('Menunggu Pemeriksaan',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Ubah Laporan',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Unggah Foto',exact:true})).toHaveCount(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('laporan-terkirim.png'),fullPage:true});expect(errors).toEqual([]);
});
test('Inspector membaca draf sendiri, pemulihan koneksi, Owner tidak membaca laporan belum disetujui',async({page},info)=>{
  await login(page,'inspector');await page.goto('/proyek');await page.getByRole('link',{name:'Proyek Penugasan Uji',exact:true}).click();const projectId=page.url().split('/').at(-1)!;
  const records=await(await page.request.get(`/api/projects/${projectId}/reports`)).json();const reportId=records.reports[0].id;
  await page.route('**/api/projects/*/reports*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Laporan belum dapat dimuat.'}})}));await projectSection(page,'laporan');await expect(page.getByRole('alert')).toContainText('Laporan belum dapat dimuat');await page.unroute('**/api/projects/*/reports*');await page.getByRole('button',{name:'Coba Lagi',exact:true}).click();await page.getByRole('link',{name:'Buka Laporan',exact:true}).click();await expect(page.getByRole('button',{name:'Ubah Laporan',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Keluar',exact:false}).click();await login(page,'owner');await page.goto(`/proyek/${projectId}/laporan`);await expect(page.getByRole('heading',{name:'Belum ada laporan yang dapat ditampilkan'})).toBeVisible();await expect(page.getByRole('button',{name:'Buat Laporan Harian',exact:true})).toHaveCount(0);expect((await page.request.get(`/api/projects/${projectId}/reports/${reportId}`)).status()).toBe(404);await page.screenshot({path:info.outputPath('owner-laporan.png'),fullPage:true});
});
