import { test, expect } from '@playwright/test';
import { projectInput } from '../support/project-fixture';
import { periods, newWeekConvention } from '../../shared/plans';

test('T11 pratinjau dan impor pekerjaan TS tersimpan tanpa data UI hardcode', async ({ page }, info) => {
  test.setTimeout(90000);
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/masuk'); await page.getByLabel('Email', { exact: true }).fill('team_leader@example.test');
  await page.getByLabel('Kata sandi', { exact: true }).fill(process.env.SIMP_TEST_PASSWORD!);
  await page.getByRole('button', { name: 'Masuk', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Proyek Anda' })).toBeVisible();
  const me = await (await page.request.get('/api/auth/me')).json();
  const response = await page.request.post('/api/projects', { headers: { origin: 'http://127.0.0.1:5174' }, data: projectInput({ projectCode: `TS-${info.project.name}-${Date.now()}`, teamLeaderId: me.user.id, endDate: '2026-12-12' }) });
  expect(response.status()).toBe(201); const project = (await response.json()).project, id = project.id;
  await page.goto(`/proyek/${id}/pekerjaan`);
  await page.getByRole('button', { name: 'Lihat Pekerjaan dari Workbook TS' }).click();
  await expect(page.getByText('7 kelompok dan 38 item', { exact: false })).toBeVisible();
  await expect(page.getByText('(sumber: 622.1201983)', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Impor Pekerjaan TS ke Proyek Ini' }).click();
  await expect(page.getByText('Pekerjaan dari workbook TS berhasil diimpor.', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.locator('.work-items-table tbody tr')).toHaveCount(45);
  await expect(page.getByRole('row', { name: /I\.1 Papan Nama Proyek/ })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Lihat Pekerjaan dari Workbook TS' })).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('ts-import.png'), fullPage: false });
  await page.goto(`/proyek/${id}/rencana`);
  await page.getByRole('button', { name: 'Buat Rencana Awal' }).click();
  await page.getByRole('button', { name: 'Lanjut ke Target' }).click();
  const options = await page.locator('#plan-item option').allTextContents();
  expect(options).toHaveLength(38);
  expect(options.slice(0, 3)).toEqual([
    'I.1 · Papan Nama Proyek',
    'I.2 · Mobilisasi dan Demobilisasi',
    'I.3 · Direksi Keet',
  ]);
  const codes = options.map(option => option.split(' · ')[0]);
  expect(codes).toEqual([...codes].sort((a, b) => a.localeCompare(b, 'id', { numeric: true })));
  const groups = await page.locator('#plan-item optgroup').evaluateAll(elements => elements.map(element => element.getAttribute('label')));
  expect(groups[0]).toContain('I · PEKERJAAN PENDAHULUAN');
  expect(groups.some(label => label?.startsWith('IV.A · '))).toBe(true);
  await page.getByLabel(/^Minggu 1\b/).fill('100');
  await page.getByRole('button', { name: 'Periksa Rencana' }).click();
  await expect(page.getByRole('alert')).toContainText('I.2 · Mobilisasi dan Demobilisasi');
  await expect(page.locator('#plan-item option:checked')).toHaveText('I.2 · Mobilisasi dan Demobilisasi');
  await page.getByRole('button', { name: 'Pratinjau target dari workbook TS' }).click();
  await expect(page.getByText('38 pekerjaan, 22 minggu.', { exact: false })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Target versi sebelumnya' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Target workbook TS' })).toBeVisible();
  await page.getByRole('button', { name: 'Gunakan target workbook TS' }).click();
  await expect(page.getByLabel(/^Minggu 1\b/)).toHaveValue('50.000000');
  await expect(page.getByLabel(/^Minggu 22\b/)).toHaveValue('50.000000');
  await page.getByLabel('Pekerjaan yang diatur').selectOption({ label: 'IV.A.8 · Pengelasan' });
  await expect(page.getByLabel(/^Minggu 1\b/)).toHaveValue('0.000000');
  await expect(page.getByLabel(/^Minggu 11\b/)).toHaveValue('12.500000');
  await page.getByRole('button', { name: 'Periksa Rencana' }).click();
  await page.getByRole('button', { name: 'Tetapkan Rencana' }).click();
  await expect(page.getByText('Rencana berhasil diterbitkan.', { exact: true })).toBeVisible();
  const saved = await (await page.request.get(`/api/projects/${id}/plans`)).json();
  const byCode = new Map<string, string>(saved.versions[0].basis.map((item: { id: string; code: string }): [string, string] => [item.code, item.id]));
  const targets = (code: string) => saved.versions[0].items.find((item: { workItemId: string }) => item.workItemId === byCode.get(code)).targets;
  expect(targets('I.2')[0]).toBe('50.000000');
  expect(targets('I.2')[21]).toBe('50.000000');
  expect(targets('IV.A.8')[10]).toBe('12.500000');
  expect(saved.versions[0].weekConvention).toBe('MONDAY_SUNDAY');
  await page.goto(`/proyek/${id}/rencana`);
  const detail = page.getByRole('combobox', { name: 'Rincian Rencana Awal' });
  await expect(detail).toBeVisible();
  expect((await detail.locator('option').allTextContents()).slice(1)).toEqual(options);
  expect(await detail.locator('optgroup').evaluateAll(elements => elements.map(element => element.getAttribute('label')))).toEqual(groups);
  await detail.selectOption({ label: 'I.1 · Papan Nama Proyek' });
  await expect(page.locator('.plan-period-table')).toContainText('Volume target');

  const candidates = await (await page.request.get(`/api/projects/${id}/candidates`)).json();
  const inspector = candidates.users.find((user: { role: string }) => user.role === 'INSPECTOR');
  expect(inspector).toBeTruthy();
  const assignment = await page.request.post(`/api/projects/${id}/team`, { headers: { origin: 'http://127.0.0.1:5174' },
    data: { userId: inspector.id, role: 'INSPECTOR', startDate: project.today, endDate: null, isActive: true } });
  expect(assignment.status()).toBe(201);
  await page.getByRole('button', { name: 'Keluar', exact: true }).click();
  await page.goto('/masuk');
  await page.getByLabel('Email', { exact: true }).fill('inspector@example.test');
  await page.getByLabel('Kata sandi', { exact: true }).fill(process.env.SIMP_TEST_PASSWORD!);
  await page.getByRole('button', { name: 'Masuk', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Proyek Anda' })).toBeVisible();
  await page.goto(`/proyek/${id}/laporan`);
  await page.getByRole('button', { name: 'Buat Laporan Harian', exact: true }).click();
  const choice = page.getByLabel('Pekerjaan 1', { exact: true });
  const reportOptions = await choice.locator('option').allTextContents();
  expect(reportOptions[0]).toBe('Catatan kegiatan tanpa pekerjaan');
  expect(reportOptions.slice(1).map(option => option.split(' · ')[0])).toEqual(codes);
  expect(await choice.locator('optgroup').evaluateAll(elements => elements.map(element => element.getAttribute('label')))).toEqual(groups);
  const itemId = byCode.get('I.2')!;
  await choice.selectOption(itemId);
  await page.getByLabel('Uraian kegiatan 1', { exact: true }).fill('Mobilisasi peralatan');
  await page.getByLabel('Volume kegiatan 1', { exact: true }).fill('0.5');
  await page.getByRole('button', { name: 'Simpan Sementara', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'LH-00001', exact: true })).toBeVisible();
  const reportId = new URL(page.url()).pathname.split('/').at(-1);
  const savedReport = await (await page.request.get(`/api/projects/${id}/reports/${reportId}`)).json();
  expect(savedReport.activities[0]).toMatchObject({ workItemId: itemId, workCode: 'I.2', workName: 'Mobilisasi dan Demobilisasi', unit: 'Ls', quantity: '0.500000' });
  await page.getByRole('button', { name: 'Ubah Laporan', exact: true }).click();
  await expect(page.getByLabel('Pekerjaan 1', { exact: true })).toHaveValue(itemId);
  await page.getByLabel('Pekerjaan 1', { exact: true }).selectOption(byCode.get('IV.A.8')!);
  await page.getByLabel('Uraian kegiatan 1', { exact: true }).fill('Pengelasan pipa');
  await page.getByLabel('Volume kegiatan 1', { exact: true }).fill('0.5');
  await page.getByRole('button', { name: 'Simpan Sementara', exact: true }).click();
  const revisedReport = await (await page.request.get(`/api/projects/${id}/reports/${reportId}`)).json();
  expect(revisedReport.activities[0]).toMatchObject({ workItemId: byCode.get('IV.A.8'), workCode: 'IV.A.8', workName: 'Pengelasan', unit: 'M', quantity: '0.500000' });
  expect(errors).toEqual([]);
});
