import { useEffect, useRef, useState } from 'react';
import { exportKinds, exportLabels, exportCellText, type ExportDocument } from '../../../shared/exports';
import { api } from '../api';
import { ActionBar, Feedback, Field, LoadingPanel, PageHeader } from '../components/ui';
import type { ReportList } from '../../../shared/reports';
import type { ProgressResult } from '../../../shared/progress';
import '../progress.css';
import { useQueryState, queryString } from '../query-state';
const readable=(value:string)=>value.replace(/Progress/g,'Kemajuan').replace(/progress/g,'kemajuan').replace(/cut-off/gi,'sampai tanggal');

export function Exports({projectId}:{projectId:string}){
  const root=`/api/projects/${projectId}`;
  const filter=useQueryState({kind:'PROGRESS',reportId:'',period:'',from:'',cutoff:'',planVersionId:'',workbookLogos:'true',preview:''});
  const {kind,reportId,period,from,cutoff,planVersionId:plan}=filter.values;
  const workbookLogos=filter.values.workbookLogos==='true';
  const field=(key:keyof typeof filter.values,value:string)=>filter.setValues(v=>({...v,[key]:value}));
  const setKind=(v:string)=>field('kind',v),setReport=(v:string)=>field('reportId',v),setPeriod=(v:string)=>field('period',v),setFrom=(v:string)=>field('from',v),setCutoff=(v:string)=>field('cutoff',v),setPlan=(v:string)=>field('planVersionId',v),setWorkbookLogos=(v:boolean)=>field('workbookLogos',String(v));
  const request=useRef(0);
  const [reports,setReports]=useState<ReportList['reports']>([]),[plans,setPlans]=useState<ProgressResult['plans']>([]),[doc,setDoc]=useState<ExportDocument|null>(null),[applied,setApplied]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
  async function load(){setLoading(true);setError('');try{const [r,p]=await Promise.all([api<ReportList>(`${root}/reports`),api<ProgressResult>(`${root}/progress`)]);setReports(r.reports);setPlans(p.plans);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  useEffect(()=>{void load();},[projectId]);
  async function preview(){
    const current=++request.current;const v=filter.applied;
    if(v.preview!=='1'){setDoc(null);return;}
    setBusy(true);setDoc(null);setError('');setNotice('');
    const q=queryString({kind:v.kind,workbookLogos:v.workbookLogos,...(v.kind==='DAILY'?{reportId:v.reportId}:{planVersionId:v.planVersionId,...(['WEEKLY','MONTHLY'].includes(v.kind)?{period:v.period}:{from:v.from,cutoff:v.cutoff})})});
    try{const result=await api<ExportDocument>(`${root}/exports?${q}`);if(current===request.current){setDoc(result);setApplied(q);}}catch(e){if(current===request.current)setError((e as Error).message);}finally{if(current===request.current)setBusy(false);}
  }
  useEffect(()=>{void preview();return()=>{request.current++;};},[filter.applied,projectId]);
  async function download(format:'pdf'|'xlsx'){setBusy(true);setError('');setNotice('');try{const response=await fetch(`${root}/exports?${applied}&format=${format}`,{credentials:'same-origin'});if(!response.ok){const body=await response.json();throw new Error(body.error?.message??'Unduhan gagal.');}const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=`simp-${doc!.kind.toLowerCase()}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setNotice(`File ${format.toUpperCase()} berhasil diunduh.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <><a className="back-link" href={`/proyek/${projectId}`}>Kembali ke proyek</a><PageHeader eyebrow="HASIL PROYEK" title="Laporan & unduhan" description="Pilih jenis laporan dan periode, periksa hasilnya, lalu unduh PDF atau Excel." />{error&&<><Feedback error>{error}</Feedback><button onClick={()=>{void load();void preview();}}>Coba Lagi</button></>}{notice&&<Feedback>{notice}</Feedback>}{loading?<LoadingPanel/>:<><form className="project-filters export-selector" onSubmit={e=>{e.preventDefault();filter.apply({...filter.values,preview:'1'});}}>
    <Field id="export-kind" label="Jenis laporan"><select id="export-kind" value={kind} onChange={e=>setKind(e.target.value as typeof kind)}>{exportKinds.map(k=><option key={k} value={k}>{readable(exportLabels[k])}</option>)}</select></Field>
    {kind==='DAILY'?<Field id="export-report" label="Laporan harian"><select id="export-report" required value={reportId} onChange={e=>setReport(e.target.value)}><option value="">Pilih laporan</option>{reports.map(r=><option key={r.id} value={r.id}>{r.reportDate} · {r.reportNumber} · revisi {r.revision}</option>)}</select></Field>:<><Field id="export-plan" label="Rencana pembanding"><select id="export-plan" value={plan} onChange={e=>setPlan(e.target.value)}><option value="">Otomatis sesuai laporan</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>{['WEEKLY','MONTHLY'].includes(kind)?<Field id="export-period" label="Nomor periode (kosong: saat ini)"><input id="export-period" type="number" min="1" max="999" value={period} onChange={e=>setPeriod(e.target.value)}/></Field>:<><Field id="export-from" label="Awal periode"><input id="export-from" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field id="export-cutoff" label="Sampai tanggal"><input id="export-cutoff" type="date" value={cutoff} onChange={e=>setCutoff(e.target.value)}/></Field></>}</>}
    <details className="disclosure"><summary>Pilihan cetak</summary><label className="checkbox-label"><input type="checkbox" checked={workbookLogos} onChange={e=>setWorkbookLogos(e.target.checked)}/> Gunakan logo dari workbook contoh</label></details><ActionBar><button className="primary" disabled={busy} type="submit">{busy?'Memproses…':'Tampilkan Laporan'}</button><button type="button" disabled={busy} onClick={()=>void load()}>Muat Ulang Pilihan</button></ActionBar></form>
    {doc&&<section aria-label="Hasil laporan"><h2>{readable(doc.title)}</h2><p className="muted">{JSON.stringify(filter.values)!==JSON.stringify(filter.applied)?'Pilihan berubah. Tampilkan laporan kembali sebelum mengunduh.':'Hasil sesuai periode dan pilihan di atas.'}</p><div className="inline-actions"><button disabled={busy||JSON.stringify(filter.values)!==JSON.stringify(filter.applied)} onClick={()=>void download('pdf')}>Unduh PDF</button><button disabled={busy||JSON.stringify(filter.values)!==JSON.stringify(filter.applied)} onClick={()=>void download('xlsx')}>Unduh Excel</button></div><details className="disclosure"><summary>Identitas dan sumber laporan</summary><dl className="detail-grid">{doc.metadata.map(([k,v])=><div key={k}><dt>{k}</dt><dd style={{overflowWrap:'anywhere'}}>{v}</dd></div>)}</dl></details>{doc.notes.map((n,i)=><p className="muted" key={i}>{readable(n)}</p>)}
      {doc.chart&&<section className="info-panel"><h2>Grafik rencana dan capaian</h2><div className="progress-table" tabIndex={0}><svg role="img" aria-label="Grafik rencana dan aktual" viewBox="0 0 1000 520" style={{minWidth:640,width:'100%',background:'white'}}>{[0,25,50,75,100].map(v=><g key={v}><text x="0" y={325-v*3}>{v}%</text><path stroke="#ddd" d={`M50 ${320-v*3}H960`}/></g>)}{doc.chart.series.map(s=>{let started=false;return <path key={s.name} fill="none" stroke={s.color} strokeWidth="3" d={s.values.map((v,i)=>{if(v===null){started=false;return '';}const move=started?'L':'M';started=true;const dates=doc.chart!.labels;const x=50+(Date.parse(dates[i])-Date.parse(dates[0]))/(Date.parse(dates.at(-1)!)-Date.parse(dates[0])||1)*900;return `${move}${x},${320-Number(v)*3}`;}).join(' ')}/>;})}<text x="50" y="345">{doc.chart.labels[0]}</text><text x="960" y="345" textAnchor="end">{doc.chart.labels.at(-1)}</text><foreignObject x="50" y="360" width="900" height="160"><div style={{fontSize:16}}>{doc.chart.series.map(s=><p key={s.name} style={{color:s.color,margin:'4px 0',overflowWrap:'anywhere'}}>{s.name}</p>)}</div></foreignObject></svg></div></section>}
      {doc.tables.map(t=><section className="info-panel" key={t.title}><h2>{readable(t.title)}</h2>{!t.rows.length?<p>Belum ada data pada periode ini.</p>:<div className="progress-table" tabIndex={0}><table className="report-read-table"><thead><tr>{t.columns.map(c=><th key={c.label}>{c.label}</th>)}</tr></thead><tbody>{t.rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j} data-label={readable(t.columns[j].label)}>{exportCellText(v,t.columns[j].numeric)}</td>)}</tr>)}</tbody></table></div>}</section>)}{doc.photos.map(p=><figure key={p.id}><img src={p.url} alt={p.caption} style={{maxWidth:'100%',maxHeight:500}}/><figcaption>{p.caption}</figcaption></figure>)}<details className="disclosure"><summary>Pratinjau cetak</summary><p>Format cetak mengikuti workbook. Geser formulir untuk melihat semua kolom.</p>{doc.layout?.map(p=><figure key={p.name} className="workbook-preview"><figcaption>Formulir {p.name}</figcaption><div className="progress-table" tabIndex={0}><img src={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(p.svg??'')}`} alt={`Layout workbook ${p.name}`} style={{display:'block',width:p.setup.orientation==='portrait'?790:1300,maxWidth:'none',background:'white'}}/></div><details><summary>Informasi format</summary><p>Template {p.source}</p></details></figure>)}</details></section>}
  </>}</>;
}
