import { useCallback, useEffect, useRef, useState } from 'react';
import { emptyReport, reportSchema, reportStatuses, workerPositions, type ReportInput, type Report, type ReportList, type Photo } from '../../../shared/reports';
import type { WorkItemRecord } from '../../../shared/work-items';
import { displayDecimal } from '../../../shared/work-items';
import { api, ApiError } from '../api';
import { ActionBar, EmptyState, Feedback, Field, LoadingPanel, PageHeader, StatusTag, useConfirmAction } from '../components/ui';
import '../reports.css';
import { ReportReview } from './ReportReview';
import type { SessionUser } from '../../../shared/contracts';
import { useQueryState, queryString } from '../query-state';
import { groupWorkItems } from '../work-item-groups';
import { photoForApi } from '../photo-upload';

function ReportSteps({step}:{step:number}) { return <ol className="workflow-steps" aria-label="Tahap laporan">{['Isi laporan','Lengkapi foto','Periksa isian','Kirim laporan'].map((label,index)=><li key={label} aria-current={step===index?'step':undefined}>{label}</li>)}</ol>; }

const message = (err: unknown) => err instanceof ApiError && Object.keys(err.fields).length ? Object.values(err.fields).join(' ') : err instanceof Error ? err.message : 'Laporan belum dapat diproses.';
type RowField<T> = { key: keyof T; label: string; type?: string; options?: readonly string[] };
function Rows<T extends object>({title,rows,fields,initial,onChange}: {title:string;rows:T[];fields:RowField<T>[];initial:()=>T;onChange:(rows:T[])=>void}) {
  return <section className="report-part"><div className="section-heading"><h3>{title}</h3><button type="button" onClick={()=>onChange([...rows,initial()])}>Tambah {title}</button></div>
    {!rows.length && <p className="muted">Belum ada {title.toLowerCase()} yang dicatat.</p>}
    {rows.map((row,index)=><div className="report-row" key={index}><div className="form-grid">{fields.map(field=><Field key={String(field.key)} id={`${title}-${index}-${String(field.key)}`} label={`${field.label} ${index+1}`}>
      {field.options ? <select id={`${title}-${index}-${String(field.key)}`} value={String(row[field.key])} onChange={e=>onChange(rows.map((old,i)=>i===index?{...old,[field.key]:e.target.value}:old))}>{field.options.map(value=><option key={value}>{value}</option>)}</select> : <input id={`${title}-${index}-${String(field.key)}`} type={field.type ?? 'text'} value={String(row[field.key])} maxLength={2000} onChange={e=>onChange(rows.map((old,i)=>i===index?{...old,[field.key]:field.type==='number'?Number(e.target.value):e.target.value}:old))} />}
    </Field>)}</div><button type="button" className="report-remove" onClick={()=>onChange(rows.filter((_,i)=>i!==index))}>Hapus {title} {index+1}</button></div>)}
  </section>;
}
function reportInput(report:Report):ReportInput {
  return { editVersion:report.editVersion,reportDate:report.reportDate,generalNotes:report.generalNotes,activities:report.activities.map(({id,workItemId,description,location,quantity,notes})=>({id,workItemId,description,location,quantity,notes})),workforce:report.workforce,weather:report.weather,materials:report.materials,problems:report.problems };
}
function ReportEditor({projectId,report,workItems,today,onCancel,onSaved}:{projectId:string;report:Report|null;workItems:WorkItemRecord[];today:string;onCancel:()=>void;onSaved:(id:string)=>Promise<void>}) {
  const [data,setData]=useState<ReportInput>(()=>report?reportInput(report):{...emptyReport(today),activities:[{id:crypto.randomUUID(),workItemId:null,description:'',location:'',quantity:null,notes:''}]}),[step,setStep]=useState(1),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const workGroups=groupWorkItems(workItems);
  const change=<K extends keyof ReportInput>(key:K,value:ReportInput[K])=>{setError('');setData(old=>({...old,[key]:value}));};
  const activity=(index:number,patch:Partial<ReportInput['activities'][number]>)=>change('activities',data.activities.map((a,i)=>i===index?{...a,...patch}:a));
  return <section className="project-section report-editor"><ReportSteps step={0}/><h2>{report?'Ubah Laporan':'Buat Laporan Harian'}</h2><p className="muted">Langkah {step} dari 4 · {['Identitas dan kegiatan','Tenaga kerja dan cuaca','Material dan masalah','Catatan dan periksa isian'][step-1]}</p>{error&&<Feedback error>{error}</Feedback>}
    <form noValidate onSubmit={async e=>{e.preventDefault();if(busy)return;const parsed=reportSchema.safeParse(data);if(!parsed.success){const issue=parsed.error.issues[0];setStep(['activities','reportDate'].includes(String(issue.path[0]))?1:['workforce','weather'].includes(String(issue.path[0]))?2:['materials','problems'].includes(String(issue.path[0]))?3:4);setError(issue.message);return;}setBusy(true);setError('');try{const result=await api<{id:string}>(`/api/projects/${projectId}/reports${report?`/${report.id}`:''}`,{method:report?'PATCH':'POST',body:JSON.stringify(data)});await onSaved(result.id);}catch(err){setError(message(err));}finally{setBusy(false);}}}><fieldset disabled={busy}>
    {step===1&&<><Field id="report-date" label="Tanggal laporan"><input id="report-date" type="date" value={data.reportDate} max={today} onChange={e=>change('reportDate',e.target.value)} /></Field><p className="muted small">Nomor laporan, identitas proyek dan hitungan hari mengikuti data proyek serta rencana yang berlaku. Tanggal material/masalah harus sama dengan tanggal laporan.</p>
      <div className="section-heading"><h3>Kegiatan</h3><button type="button" onClick={()=>change('activities',[...data.activities,{id:crypto.randomUUID(),workItemId:null,description:'',location:'',quantity:null,notes:''}])}>Tambah Kegiatan</button></div>
      {data.activities.map((a,index)=><section className="report-row" key={a.id}><div className="form-grid"><Field id={`work-${index}`} label={`Pekerjaan ${index+1}`}><select id={`work-${index}`} value={a.workItemId??''} onChange={e=>activity(index,{workItemId:e.target.value||null,quantity:null})}><option value="">Catatan kegiatan tanpa pekerjaan</option>{workGroups.map(group=><optgroup key={group.items[0].id} label={group.label}>{group.items.map(w=><option key={w.id} value={w.id}>{w.code} · {w.name} ({w.unit})</option>)}</optgroup>)}</select></Field><Field id={`description-${index}`} label={`Uraian kegiatan ${index+1}`}><textarea id={`description-${index}`} value={a.description} onChange={e=>activity(index,{description:e.target.value})} /></Field><Field id={`location-${index}`} label={`Lokasi kegiatan ${index+1}`}><input id={`location-${index}`} value={a.location} onChange={e=>activity(index,{location:e.target.value})} /></Field><Field id={`quantity-${index}`} label={`Volume kegiatan ${index+1}`}><input id={`quantity-${index}`} inputMode="decimal" disabled={!a.workItemId} value={a.quantity??''} onChange={e=>activity(index,{quantity:e.target.value?e.target.value.replace(',','.'):null})} /></Field><Field id={`notes-${index}`} label={`Catatan kegiatan ${index+1}`}><textarea id={`notes-${index}`} value={a.notes} onChange={e=>activity(index,{notes:e.target.value})} /></Field></div><p className="muted small">{a.workItemId?`Satuan: ${workItems.find(w=>w.id===a.workItemId)?.unit}. Kosongkan volume untuk catatan tanpa volume.`:'Catatan tanpa volume tidak menambah kemajuan.'}</p><button type="button" onClick={()=>change('activities',data.activities.filter((_,i)=>i!==index))}>Hapus Kegiatan {index+1}</button></section>)}</>}
    {step===2&&<><Rows<ReportInput['workforce'][number]> title="Tenaga Kerja" rows={data.workforce} onChange={rows=>change('workforce',rows.map(w=>({...w,category:workerPositions.indexOf(w.position)<4?'Manajemen':'Lapangan'})))} initial={()=>({category:'Lapangan',position:'Pekerja',quantity:1,identity:'',workingHours:'8',notes:''})} fields={[{key:'position',label:'Jenis tenaga kerja',options:workerPositions},{key:'quantity',label:'Jumlah orang',type:'number'},{key:'identity',label:'Identitas opsional'},{key:'workingHours',label:'Jam kerja'},{key:'notes',label:'Catatan tenaga kerja'}]} />
      <Rows<ReportInput['weather'][number]> title="Cuaca" rows={data.weather} onChange={rows=>change('weather',rows)} initial={()=>({period:'PAGI',condition:'BAIK',startTime:'08:00',endTime:'12:00',notes:''})} fields={[{key:'period',label:'Waktu cuaca',options:['PAGI','SIANG','SORE','MALAM']},{key:'condition',label:'Kondisi',options:['BAIK','GERIMIS','HUJAN']},{key:'startTime',label:'Jam mulai',type:'time'},{key:'endTime',label:'Jam selesai',type:'time'},{key:'notes',label:'Catatan cuaca'}]} /><p className="muted">Malam boleh tidak diisi jika tidak ada kegiatan. Jam dicatat dalam tanggal yang sama.</p></>}
    {step===3&&<><Rows<ReportInput['materials'][number]> title="Material atau Alat" rows={data.materials} onChange={rows=>change('materials',rows)} initial={()=>({type:'DITERIMA',name:'',quantity:'0',unit:'',date:data.reportDate,reason:'',notes:''})} fields={[{key:'type',label:'Penerimaan',options:['DITERIMA','DITOLAK']},{key:'name',label:'Nama material atau alat'},{key:'quantity',label:'Jumlah material'},{key:'unit',label:'Satuan material'},{key:'date',label:'Tanggal material',type:'date'},{key:'reason',label:'Alasan penolakan'},{key:'notes',label:'Catatan material'}]} />
      <Rows<ReportInput['problems'][number]> title="Masalah" rows={data.problems} onChange={rows=>change('problems',rows)} initial={()=>({problem:'',date:data.reportDate,location:'',impact:'',resolution:'',status:'Belum Ditangani',notes:''})} fields={[{key:'problem',label:'Uraian masalah'},{key:'date',label:'Tanggal masalah',type:'date'},{key:'location',label:'Lokasi masalah'},{key:'impact',label:'Dampak'},{key:'resolution',label:'Penyelesaian'},{key:'status',label:'Status masalah',options:['Belum Ditangani','Sedang Ditangani','Selesai']},{key:'notes',label:'Catatan masalah'}]} /></>}
    {step===4&&<><Field id="report-notes" label="Catatan umum"><textarea id="report-notes" rows={4} value={data.generalNotes} onChange={e=>change('generalNotes',e.target.value)} /></Field><p>Tanggal {data.reportDate} · {data.activities.length} kegiatan · {data.workforce.length} jenis tenaga kerja · {data.materials.length} material/alat · {data.problems.length} masalah.</p><p>Simpan isian untuk melanjutkan ke foto. Laporan belum dikirim sampai Anda menekan Kirim untuk Diperiksa.</p></>}
    <ActionBar sticky>{step>1&&<button type="button" onClick={()=>setStep(step-1)}>Sebelumnya</button>}{step<4&&<button type="button" onClick={()=>setStep(step+1)}>Lanjut</button>}<button className="primary" type="submit">{busy?'Menyimpan…':step===4?'Simpan & Lanjut ke Foto':'Simpan Sementara'}</button><button type="button" onClick={onCancel}>Batal</button></ActionBar></fieldset></form>
  </section>;
}
function PhotoGallery({photos,onDelete}:{photos:Photo[];onDelete?:(photo:Photo)=>void}) {
  return <div className="report-gallery">{photos.map(photo=><figure key={photo.id}><a href={photo.url} target="_blank" rel="noreferrer"><img src={photo.url} alt={photo.caption} loading="lazy" /></a><figcaption><strong>{photo.caption}</strong><p>{photo.takenDate} · {photo.location||'Lokasi belum diisi'}</p><p className="muted small">Diunggah {photo.uploadedByName} · {new Date(photo.createdAt).toLocaleString('id-ID')}</p><a href={`/proyek/${photo.url.split('/')[3]}/laporan/${photo.reportId}`}>{photo.reportNumber}</a>{onDelete&&<button onClick={()=>onDelete(photo)}>Hapus Foto</button>}</figcaption></figure>)}</div>;
}
function PhotoUpload({report,projectId,reload}:{report:Report;projectId:string;reload:()=>Promise<void>}) {
  const [file,setFile]=useState<File|null>(null),[activityId,setActivityId]=useState(report.activities[0]?.id??''),[caption,setCaption]=useState(''),[location,setLocation]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  return <form className="report-row" noValidate onSubmit={async e=>{e.preventDefault();if(busy)return;if(!file||!caption.trim()){setError('Pilih foto dan isi keterangannya.');return;}if(!['image/jpeg','image/png'].includes(file.type)||file.size>5*1024*1024){setError('Pilih foto JPEG/PNG maksimal 5 MiB.');return;}setBusy(true);setError('');try{const {data,mime}=await photoForApi(file);await api(`/api/projects/${projectId}/reports/${report.id}/photos`,{method:'POST',body:JSON.stringify({editVersion:report.editVersion,activityId,caption,location,takenDate:report.reportDate,mime,data}),signal:AbortSignal.timeout(60000)});await reload();}catch(err){setError(message(err));}finally{setBusy(false);}}}><h3>Unggah Foto</h3>{error&&<Feedback error>{error}</Feedback>}<fieldset disabled={busy}><div className="form-grid"><Field id="photo-file" label="Berkas foto"><input id="photo-file" type="file" accept="image/jpeg,image/png" onChange={e=>setFile(e.target.files?.[0]??null)} /></Field><Field id="photo-activity" label="Kegiatan terkait"><select id="photo-activity" value={activityId} onChange={e=>setActivityId(e.target.value)}>{report.activities.map(a=><option key={a.id} value={a.id}>{a.description}</option>)}</select></Field><Field id="photo-caption" label="Keterangan foto"><input id="photo-caption" value={caption} onChange={e=>setCaption(e.target.value)} /></Field><Field id="photo-location" label="Lokasi foto"><input id="photo-location" value={location} onChange={e=>setLocation(e.target.value)} /></Field></div><p className="muted small">Tanggal foto: {report.reportDate}. JPEG/PNG maksimal 5 MiB dan 20 juta piksel; maksimal 20 foto per laporan. Foto disimpan sebagai JPEG.</p><button className="primary" disabled={busy}>{busy?'Mengunggah…':'Unggah Foto'}</button></fieldset></form>;
}
function Detail({report,projectId,onEdit,reload,onDeleted}:{report:Report;projectId:string;onEdit:()=>void;reload:()=>Promise<void>;onDeleted:()=>void}) {
  const [review,setReview]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const { confirm, confirmation } = useConfirmAction();
  useEffect(()=>{if(window.location.hash==='#report-photos')document.getElementById('report-photos')?.focus();},[report.id]);
  const action=async(url:string,method:string,after:()=>void|Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await api(url,{method,body:JSON.stringify({editVersion:report.editVersion})});await after();}catch(err){setError(message(err));}finally{setBusy(false);}};
  return <><PageHeader title={report.reportNumber} description={<>{reportStatuses[report.status]} · {report.reportDate} · {report.createdByName}</>} actions={report.canEdit&&<button onClick={onEdit} disabled={busy}>Ubah Laporan</button>} />{error&&<Feedback error>{error}</Feedback>}
    {report.canEdit&&<><ReportSteps step={review?2:1}/><section className="next-action"><h2>{review?'Periksa laporan sebelum dikirim':'Lengkapi laporan Anda'}</h2><p>{review?'Periksa kegiatan, kondisi lapangan, dan foto. Pengiriman akan mengunci isian laporan.':'Isian tersimpan. Lengkapi foto untuk setiap kegiatan bervolume, lalu periksa laporan.'}</p><div className="report-task-actions"><a className="button" href="#report-photos">Lengkapi Foto</a>{review?<button className="primary" disabled={busy} onClick={()=>void action(`/api/projects/${projectId}/reports/${report.id}/submit`,'POST',reload)}>Kirim untuk Diperiksa</button>:<button className="primary" onClick={()=>setReview(true)}>Periksa Sebelum Kirim</button>}{review&&<button onClick={()=>setReview(false)}>Kembali Memeriksa</button>}</div></section></>}
    <ReportReview key={report.id} report={report} reload={reload} />
    <div className="inline-actions"><a className="button" href={`/proyek/${projectId}/ekspor?kind=DAILY&reportId=${report.id}`}>Pratinjau cetak / Unduh</a></div>
    <details className="disclosure"><summary>Identitas laporan dan kontrak</summary><p>{report.projectName} · Kontrak {report.contractNumber}</p><p>Nama kontraktor: {report.contractorName || 'Belum diisi'} <span className="muted">(data proyek saat ini)</span></p><p>Rencana: {report.planName} · {report.startDate} — {report.endDate}</p><p>Hari ke-{report.calendar.day} · Minggu ke-{report.calendar.week} · Durasi {report.calendar.durationDays} hari · Sisa {report.calendar.remainingDays} hari</p><p>Total tenaga kerja: <strong>{report.workforceTotal} orang</strong></p><p className="muted">Hanya versi yang disetujui dan masih berlaku menjadi sumber resmi. Perhitungan tersedia melalui Rincian kemajuan.</p></details>
    <section className="project-section"><h2>Kegiatan</h2>{!report.activities.length ? <p>Tidak ada kegiatan dicatat.</p> : <div className="responsive-table"><table className="adaptive-table"><thead><tr><th>Uraian</th><th>Pekerjaan</th><th>Volume</th><th>Lokasi</th><th>Catatan</th></tr></thead><tbody>{report.activities.map(a=><tr key={a.id}><td data-label="Uraian"><strong>{a.description}</strong></td><td data-label="Pekerjaan">{a.workItemId?`${a.workCode} · ${a.workName}`:'Catatan tanpa pekerjaan'}</td><td data-label="Volume">{a.quantity===null?'Tanpa volume':`${displayDecimal(a.quantity,6)} ${a.unit}`}</td><td data-label="Lokasi">{a.location||'—'}</td><td data-label="Catatan">{a.notes||'—'}</td></tr>)}</tbody></table></div>}</section>
    <section className="info-panel"><h2>Tenaga kerja dan cuaca</h2><h2>Tenaga kerja</h2>{!report.workforce.length?<p>Tidak ada tenaga kerja dicatat.</p>:<div className="responsive-table"><table className="adaptive-table"><thead><tr><th>Posisi</th><th>Kategori</th><th>Jumlah</th><th>Jam kerja</th><th>Identitas/catatan</th></tr></thead><tbody>{report.workforce.map((w,i)=><tr key={i}><td data-label="Posisi">{w.position}</td><td data-label="Kategori">{w.category}</td><td data-label="Jumlah">{w.quantity} orang</td><td data-label="Jam kerja">{w.workingHours} jam</td><td data-label="Identitas/catatan">{[w.identity,w.notes].filter(Boolean).join(' · ')||'—'}</td></tr>)}</tbody></table></div>}<h2>Cuaca</h2>{!report.weather.length?<p>Tidak ada cuaca dicatat.</p>:<div className="responsive-table"><table className="adaptive-table"><thead><tr><th>Waktu</th><th>Kondisi</th><th>Jam</th><th>Catatan</th></tr></thead><tbody>{report.weather.map(w=><tr key={w.period}><td data-label="Waktu">{w.period}</td><td data-label="Kondisi">{w.condition}</td><td data-label="Jam">{w.startTime}–{w.endTime}</td><td data-label="Catatan">{w.notes||'—'}</td></tr>)}</tbody></table></div>}</section>
    <section className="project-section"><h2>Material dan alat</h2>{!report.materials.length?<p>Tidak ada material/alat dicatat.</p>:<div className="responsive-table"><table className="adaptive-table"><thead><tr><th>Nama</th><th>Status</th><th>Jumlah</th><th>Tanggal</th><th>Keterangan</th></tr></thead><tbody>{report.materials.map((m,i)=><tr key={i}><td data-label="Nama">{m.name}</td><td data-label="Status">{m.type}</td><td data-label="Jumlah">{m.quantity} {m.unit}</td><td data-label="Tanggal">{m.date}</td><td data-label="Keterangan">{[m.reason,m.notes].filter(Boolean).join(' · ')||'—'}</td></tr>)}</tbody></table></div>}<h2>Masalah lapangan</h2>{!report.problems.length?<p>Tidak ada masalah dicatat.</p>:<div className="responsive-table"><table className="adaptive-table"><thead><tr><th>Masalah</th><th>Tanggal/lokasi</th><th>Status</th><th>Dampak</th><th>Penyelesaian</th></tr></thead><tbody>{report.problems.map((p,i)=><tr key={i}><td data-label="Masalah"><strong>{p.problem}</strong><small>{p.notes}</small></td><td data-label="Tanggal/lokasi">{p.date}<br />{p.location}</td><td data-label="Status">{p.status}</td><td data-label="Dampak">{p.impact||'—'}</td><td data-label="Penyelesaian">{p.resolution||'—'}</td></tr>)}</tbody></table></div>}<h2>Catatan umum</h2><p>{report.generalNotes||'Tidak ada catatan.'}</p></section>
    <section className="project-section" id="report-photos" tabIndex={-1}><h2>Foto kegiatan</h2><p>Setiap kegiatan dengan volume positif wajib memiliki foto sebelum dikirim. Foto hanya dapat dibuka oleh pihak yang berhak membaca laporan.</p>{!report.photos.length&&<p>Belum ada foto.</p>}<PhotoGallery photos={report.photos} onDelete={report.canEdit?async photo=>{if(await confirm({title:'Hapus foto?',message:`Foto “${photo.caption}” akan dihapus dari laporan ini.`,confirmLabel:'Hapus foto',danger:true}))void action(`/api/projects/${projectId}/reports/${report.id}/photos/${photo.id}`,'DELETE',reload);}:undefined} />{report.canEdit&&<PhotoUpload key={report.editVersion} report={report} projectId={projectId} reload={reload} />}</section>

    {report.canDelete&&<details className="disclosure"><summary>Tindakan lainnya</summary><button className="report-remove" disabled={busy} onClick={async()=>{if(await confirm({title:'Hapus draf laporan?',message:'Draf laporan beserta seluruh fotonya akan dihapus. Tindakan ini tidak dapat dibatalkan.',confirmLabel:'Hapus draf',danger:true}))void action(`/api/projects/${projectId}/reports/${report.id}`,'DELETE',onDeleted);}}>Hapus Draf</button></details>}
    {confirmation}
  </>;
}
export function Reports({projectId,user}:{projectId:string;user:SessionUser}) {
  const requestNumber=useRef(0);
  const reportId=window.location.pathname.split('/')[4];
  const defaultView=user.role==='INSPECTOR'?'unfinished':['TEAM_LEADER','ENGINEER'].includes(user.role)?'waiting':'all';
  const filter=useQueryState({from:'',to:'',week:'',month:'',status:'',createdBy:'',view:defaultView});
  const {view,...apiFilters}=filter.applied;
  const query=queryString({...apiFilters,...(view==='waiting'?{status:'SUBMITTED'}:{}),...(view==='unfinished'?{createdBy:user.id}:{})});
  const [list,setList]=useState<ReportList|null>(null),[report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[editing,setEditing]=useState(false),[creating,setCreating]=useState(false),[notice,setNotice]=useState('');
  const load=useCallback(async()=>{
    const current=++requestNumber.current;setError('');
    try{const data=await api<ReportList>(`/api/projects/${projectId}/reports${!reportId&&query?`?${query}`:''}`);const detail=reportId?await api<Report>(`/api/projects/${projectId}/reports/${encodeURIComponent(reportId)}`):null;if(current===requestNumber.current){setList(data);setReport(detail);}}
    catch(err){if(current===requestNumber.current)setError(message(err));}finally{if(current===requestNumber.current)setLoading(false);}
  },[projectId,reportId,query]);
  useEffect(()=>{void load();return()=>{requestNumber.current++;};},[load]);
  const reset=()=>filter.apply({from:'',to:'',week:'',month:'',status:'',createdBy:'',view:'all'});
  if(loading)return <LoadingPanel/>;
  if(!list)return <><Feedback error>{error||'Laporan belum tersedia.'}</Feedback><button onClick={()=>void load()}>Coba Lagi</button><button onClick={reset}>Bersihkan Filter</button></>;
  const link=`/proyek/${projectId}/laporan`;
  const visible=view==='unfinished'?list.reports.filter(r=>['DRAFT','NEEDS_REVISION'].includes(r.status)):list.reports;
  return <><a className="back-link" href={reportId?link:`/proyek/${projectId}`}>← {reportId?'Daftar Laporan':'Ringkasan proyek'}</a>{notice&&<Feedback>{notice}</Feedback>}{error&&<><Feedback error>{error}</Feedback><button onClick={()=>void load()}>Coba Lagi</button></>}
    {(creating||editing)?<ReportEditor projectId={projectId} report={editing?report:null} workItems={list.workItems} today={list.today} onCancel={()=>{setEditing(false);setCreating(false);}} onSaved={async id=>{if(!reportId){window.location.assign(`${link}/${id}`);return;}await load();setEditing(false);setNotice('Isian tersimpan. Lanjutkan melengkapi foto dan periksa sebelum dikirim.');}}/>:report?<Detail report={report} projectId={projectId} onEdit={()=>{setEditing(true);setNotice('');window.scrollTo(0,0);}} reload={load} onDeleted={()=>window.location.assign(link)}/>:reportId?<Feedback error>Detail laporan belum dapat dimuat. Coba lagi.</Feedback>:<>
      <PageHeader eyebrow="LAPORAN PROYEK" title="Laporan Harian" description={view==='waiting'?'Laporan yang menunggu pemeriksaan.':view==='unfinished'?'Laporan Anda yang belum dikirim atau perlu diperbaiki.':'Catatan kegiatan dan kondisi lapangan.'} actions={list.canCreate&&<button className="primary" onClick={()=>setCreating(true)}>Buat Laporan Harian</button>} />
      <div className="inline-actions" aria-label="Pilihan daftar laporan"><button aria-pressed={view==='all'} onClick={reset}>Semua laporan</button>{user.role!=='OWNER'&&<button aria-pressed={view==='waiting'} onClick={()=>filter.apply({...filter.applied,view:'waiting',status:''})}>Menunggu pemeriksaan</button>}{user.role==='INSPECTOR'&&<button aria-pressed={view==='unfinished'} onClick={()=>filter.apply({...filter.applied,view:'unfinished',status:''})}>Perlu saya selesaikan</button>}</div>
      <section className="info-panel"><h2>Filter laporan{query?' · aktif':''}</h2><form className="project-filters" onSubmit={e=>{e.preventDefault();filter.apply({...filter.values,view:'all'});}}><p>Minggu mengikuti aturan rencana yang dipakai laporan; rencana baru memakai Senin–Minggu.</p>{(['from','to','week','month'] as const).map(key=><Field key={key} id={'filter-'+key} label={{from:'Tanggal awal',to:'Tanggal akhir',week:'Minggu ke-',month:'Bulan ke-'}[key]}><input id={'filter-'+key} type={key==='from'||key==='to'?'date':'number'} min={key==='week'||key==='month'?1:undefined} value={filter.values[key]} onChange={e=>filter.setValues({...filter.values,[key]:e.target.value})}/></Field>)}
      <Field id="filter-status" label="Status laporan"><select id="filter-status" value={filter.values.status} onChange={e=>filter.setValues({...filter.values,status:e.target.value})}><option value="">Semua status</option>{Object.entries(reportStatuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field>
      <Field id="filter-creator" label="Pembuat laporan"><select id="filter-creator" value={filter.values.createdBy} onChange={e=>filter.setValues({...filter.values,createdBy:e.target.value})}><option value="">Semua pembuat</option>{list.creators.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><button type="submit">Terapkan Filter</button><button type="button" onClick={reset}>Bersihkan Filter</button></form></section>
      {!error&&(!visible.length?<EmptyState title="Belum ada laporan yang dapat ditampilkan"><p>{view==='all'?'Belum ada laporan sesuai pilihan Anda.':'Tidak ada laporan dalam antrean ini. Buka Semua laporan untuk melihat yang lainnya.'}</p></EmptyState>:<div className="responsive-table"><table className="adaptive-table report-list-table"><thead><tr><th>Nomor laporan</th><th>Tanggal</th><th>Pembuat</th><th>Status</th><th>Tindakan</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td data-label="Nomor laporan"><a href={`${link}/${r.id}`}><strong>{r.reportNumber}</strong></a></td><td data-label="Tanggal">{r.reportDate}</td><td data-label="Pembuat">{r.createdByName}</td><td data-label="Status"><StatusTag tone={r.status==='APPROVED'?'success':r.status==='NEEDS_REVISION'?'danger':r.status==='SUBMITTED'?'warning':'neutral'}>{reportStatuses[r.status]}</StatusTag></td><td data-label="Tindakan"><a href={`${link}/${r.id}`}>Buka Laporan</a></td></tr>)}</tbody></table></div>)}
    </>}
  </>;
}
